name       : freefilesync
version    : 9.9
release    : 1
source     :
    - https://www.freefilesync.org/download/FreeFileSync_9.9_Source.zip : 43edd3c8546bd5a44c5d353811389a68b148f0655c006c13f4357f3579b9a970
    - https://sourceforge.net/projects/xbrz/files/xBRZ/xBRZ_1.6.zip : 8d51e52a9264d09117cf434b7fcb46a17ee4285a00432554ba47fa86ac4511ce
license    : GPL-3.0
component  : network.util
summary    : Free backup software to synchronize files and folders
description: |
    FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    pushd ..
    %apply_patches

    XBRZ_NAME=$(basename $sources/xBRZ*.zip)
    mkdir -p xBRZ/src
    unzip $sources/$XBRZ_NAME -d xBRZ/src
    popd
build      : |
    pushd Source
    %make
    pushd RealTimeSync
    %make
    popd
    popd
install    : |
    install -dm00755 $installdir/usr/bin
    cp Build/FreeFileSync $installdir/usr/bin
    cp Build/RealTimeSync $installdir/usr/bin

    install -dm00644 $installdir/usr/share/FreeFileSync
    cp -R Build/Languages/ \
    Build/Help/ \
    Build/*.wav \
    Build/Resources.zip \
    $installdir/usr/share/FreeFileSync

    install -dm00644 $installdir/usr/share/doc/FreeFileSync
    cp ../Changelog.txt $installdir/usr/share/doc/FreeFileSync/changelog
    gzip $installdir/usr/share/doc/FreeFileSync/changelog

    install -Dm00644 $pkgfiles/FreeFileSync.desktop $installdir/usr/share/applications/FreeFileSync.desktop
    install -Dm00644 $pkgfiles/RealTimeSync.desktop $installdir/usr/share/applications/RealTimeSync.desktop

    unzip Build/Resources.zip FreeFileSync.png RealTimeSync.png
    install -Dm00644 FreeFileSync.png $installdir/usr/share/pixmaps/FreeFileSync.png
    install -Dm00644 RealTimeSync.png $installdir/usr/share/pixmaps/RealTimeSync.png
