name       : freefilesync
version    : 10.3
release    : 4
source     :
    - https://freefilesync.org/download/FreeFileSync_10.3_Source.zip : 9e958ae968d4e8aff40e547edc575735da73fe0dd9d2558b060f11471a24a0ef
license    : GPL-3.0-or-later
component  : network.util
summary    : Free backup software to synchronize files and folders
description: |
    FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - pkgconfig(xxf86vm)
    - libboost-devel
    - wxwidgets30-devel
setup      : |
    pushd ..
    %apply_patches
    popd
build      : |
    %make -C Source
    %make -C Source/RealTimeSync
install    : |
    %make_install -C Source
    %make_install -C Source/RealTimeSync

    install -Dm00644 $pkgfiles/FreeFileSync.desktop $installdir/usr/share/applications/FreeFileSync.desktop
    install -Dm00644 $pkgfiles/RealTimeSync.desktop $installdir/usr/share/applications/RealTimeSync.desktop

    unzip Build/Resources.zip FreeFileSync.png RealTimeSync.png
    install -Dm00644 FreeFileSync.png $installdir/usr/share/pixmaps/FreeFileSync.png
    install -Dm00644 RealTimeSync.png $installdir/usr/share/pixmaps/RealTimeSync.png

    # Set file permissions
    find $installdir/usr/share/FreeFileSync -type f -print0 | xargs -0 chmod 644
    find $installdir/usr/share/doc/FreeFileSync -type f -print0 | xargs -0 chmod 644
